before_install:
    git clone git://github.com/Krozark/libmgf.git
    && cd libmgf
    && cmake .
    && sudo make install
    && cd ..
    && git clone https://github.com/Krozark/cpp-Socket
    && cd cpp-Socket
    && cmake .
    && sudo make install
    && cd ..
    && git clone https://github.com/Krozark/monitoring
    && cd monitoring
    && cmake .
    && sudo make install
    && cd ..



install: 
    ./build.sh
    && make exe

language: cpp

compiler: gcc

script : make
