before_install:
    git clone git://github.com/Krozark/libmgf.git
    && cd libmgf
    && ./build.sh
    && cd ..
    && git clone https://github.com/Krozark/cpp-Socket
    && cd cpp-Socket
    && ./build.sh
    && cd ..
    && git clone https://github.com/Krozark/monitoring
    && cd monitoring
    && ./build
    && cd ..



install: 
    cd libmgf 
    && sudo make install
    && cd ..
    && cd cpp-Socket
    && sudo make install
    && cd ..
    && cd monitoring
    && sudo make install
    && dc ..
    && ./build.sh

language: cpp

compiler: gcc

script : make
