before_install:
    git clone git://github.com/Krozark/libmgf.git
    && cd libmgf
    && ./build.sh
    cd ..


install: 
    cd libmgf 
    && sudo make install
    && cd ..

language: cpp

compiler: gcc

script : make
